---
namespace: trippsc2
name: packer
version: 1.4.1
readme: README.md
authors:
  - Jim Tarpley (@trippsc2)
description: This collection contains roles for installing and running HashiCorp Packer.

license_file: 'LICENSE'

tags:
  - cloud
  - infrastructure
  - tools

dependencies:
  trippsc2.hashicorp: ">=1.0.0"

repository: https://github.com/trippsc2/ansible-collection-packer.git

manifest:
  directives:
    - recursive-include roles/* *.md
    - recursive-include roles/*/files **
    - exclude galaxy.yml galaxy.yaml MANIFEST.json FILES.json *.tar.gz
    - recursive-exclude tests/output **
    - recursive-exclude roles/*/molecule **
    - recursive-exclude molecule **
    - global-exclude /.* /__pycache__
